### ISSUE TITLE
Trabajo final

### ISSUE THREAD

**Issue by alarco** [alarco/decont#1]
Hola Tomás,

Acabo de hacer un push con el trabajo final. 
No se si será importante, pero la carpeta en la que he estado trabajando se llama decon en vez de decont.

Saludos
Alicia

**Comment by tdido** [comment]
Fenomenal, Alicia, buen trabajo.

El único detalle que te puedo comentar, que no afecta a tu solución pero simplemente para que lo tengas en cuenta para el futuro, es que en lugar de hacer `basename $(echo $fname)` podrías hacer directamente `basename $fname`.

Pero más allá de esa pavada, funciona perfectamente.
